services:
  app:
    image: ghcr.io/neatplex/nightell-core:latest
    ports:
      - ${APP_EXPOSED_PORT:-0}:8080
    volumes:
      - ./configs:/app/configs
      - ./storage:/app/storage
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.37
    ports:
      - 127.0.0.1:${MYSQL_EXPOSED_PORT:-0}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 3s
      timeout: 20s
      retries: 150

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON_URL=https://nightell.neatplex.com/swagger.json
    restart: always
    ports:
      - "${SWAGGER_EXPOSED_PORT:-0}:8080"