services:
  mysql:
    image: ghcr.io/getimages/mysql:8.0.35-debian
    ports:
      - 127.0.0.1:${MYSQL_EXPOSED_PORT:-0}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./.docker/mysql:/var/lib/mysql
